### ISSUE TITLE
摘要微调的时候缺少数据处理文件

### ISSUE THREAD

**Issue by YaxinFAN1** [xu-song/k-plug#2]
![image](https://user-images.githubusercontent.com/36947158/159743321-5fb86c9e-4e5e-4006-b59c-8d3a37bf747c.png)
examples/kplug下是不是缺少对应的数据处理文件

**Comment by xu-song** [comment]
数据样例已经添加  
https://github.com/xu-song/k-plug/tree/master/data_sample/sum/cepsum/jiadian/raw

[inference_cepsum_demo.sh](https://github.com/xu-song/k-plug/blob/master/inference_cepsum_demo.sh)可以直接跑通流程

更简单的，可以用提供的docker镜像来运行
