### ISSUE TITLE
工程结构图

### ISSUE THREAD

**Issue by AlexYoung757** [xu-song/k-plug#4]
冒昧问一下，能否给个工程说明图，每个文件功能做个解释说明

**Comment by xu-song** [comment]
这项目的架构，与 fairseq官方是保持一致的，网上找找fairseq的教程就行。
https://github.com/facebookresearch/fairseq/tree/main/fairseq

- model: 定义的模型结构，核心函数看forward就行
- data: 不同的任务，定义不同的数据格式
- criterion: 定义的loss function，比如我们定义了多任务学习的loss function，定义了序列标注的loss function（官方没提供）
- task: 将data和model串起来

**Comment by AlexYoung757** [comment]
> 

了解。谢谢解答

**Comment by xu-song** [comment]
另外，如果对fairseq不熟，我们还提供了huggingface版本的model

https://github.com/xu-song/k-plug/tree/master/examples/kplug_hf
